version: '3.1'

services:
  db: 
    container_name: ${DB_NAME}
    image: postgres:14.4
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  pgAmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=david@hotmail.com
    volumes:
      - ./pgadmin:/var/lib/pgadmin

# volumes:
#   postgres-db: 
#     external: true